### ISSUE TITLE
Negated media queries not supported

### ISSUE THREAD

**Issue by jonaswalden** [jonaswalden/demq#5]
Using the `not` operator to negate conditions in a media query is not handled correctly by package.

Filtering the following css with options `{minValue: 200}`:

```css
@media (min-width: 200px) {
  .component { content: "want" }
}
@media not (min-width: 200px) {
  .component { content: "don't want" }
}
```

Incorrectly results in this:

```css
.component { content: "want" }
.component { content: "don't want" }
```

Instead of this:

```css
.component { content: "want" }
```
